version: '3.8'
services:
    web:
        build: .
        user: root
        ports:
            - "8000:8000"
        volumes:
            - .:/home/appuser/app
        environment:
            - SPACY_MODEL=da_core_news_lg
            - LEMMATIZER_ENDPOINT=TODO