version: '3.8'
services:
    web:
        build: .
        user: root
        ports:
            - "8000:8000"
        volumes:
            - .:/home/appuser/app
        environment:
            - QUEUE_PATH=./queue/
            - NJ_SPACY_MODEL=da_core_news_lg
            - LEMMATIZER_ENDPOINT=http://130.225.57.27/lemmatizer/
            - WORD_COUNT_DATA_ENDPOINT=http://localhost:5000/wordcount
            - TRIPLE_DATA_ENDPOINT=http://localhost:5000/knowledge_graph
            - ONTOLOGY_NAMESPACE=Knox
        command: python3 app.py
    performance_test:
        build:
            context: .
            dockerfile: ./tests/performance_test/Dockerfile
        user: root
        ports:
            - "5000:5000"
            - "5050:5050"
        volumes:
            - .:/home/appuser/app
        environment:
            - QUEUE_PATH=./queue/
            - NJ_SPACY_MODEL=da_core_news_lg
            - LEMMATIZER_ENDPOINT=http://host.docker.internal:5050/
            - WORD_COUNT_DATA_ENDPOINT=http://localhost:5000/wordcount
            - PYTHONPATH=$PYTHONPATH:/home/appuser/app/
            - PERFORMANCE_OUTPUT_FOLDER=/home/appuser/app/tests/performance_test/output/
        working_dir: /home/appuser/app
        command: python3 ./tests/performance_test/test.py