version: '3.8'
services:
    web:
        build: .
        user: root
        ports:
            - "8000:8000"
        volumes:
            - .:/home/appuser/app
        environment:
            - GF_PATTERN_PATH=./resources/patterns.jsonl
            - QUEUE_PATH=./queue/
            - NJ_SPACY_MODEL=models/nj_model
            - GF_SPACY_MODEL=./models/gf_spacy_model
            - LEMMATIZER_ENDPOINT=http://localhost/lemmatizer/
            - WORD_COUNT_DATA_ENDPOINT=http://localhost:5000/wordcount
            - TRIPLE_DATA_ENDPOINT=http://localhost:5000/query
            - ONTOLOGY_NAMESPACE=http://www.Knox.test/
            
