version: '3.8'
services:
    web:
        build: .
        user: root
        ports:
            - "8000:8000"
        volumes:
            - .:/home/appuser/app
        environment:
            - QUEUE_PATH=./queue/
            - NJ_SPACY_MODEL=da_core_news_lg
            - GF_SPACY_MODEL=./models/gf_spacy_model
            - GF_PATTERN_PATH=./resources/patterns.jsonl
            - LEMMATIZER_ENDPOINT=http://130.225.57.27/lemmatizer/
            - WORD_COUNT_DATA_ENDPOINT=http://localhost:5000/wordcount
            - TRIPLE_DATA_ENDPOINT=http://localhost:5000/knowledge_graph
            - ONTOLOGY_NAMESPACE=Knox
            
