version: '3.3'
services:
    web:
        build: .
        user: root
        ports:
            - "5050:8000"
        environment:
            - QUEUE_PATH=./queue/
            - NJ_SPACY_MODEL=da_core_news_lg
            - LEMMATIZER_ENDPOINT=http://130.225.57.27/lemmatizer/
            - WORD_COUNT_DATA_ENDPOINT=http://192.38.49.147:5000/wordcount
        restart: always
        command: python3 app.py

